services:

  mysql:
    image: mysql:8.0

    container_name: mysql-container

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot3
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .

    container_name: springboot-app

    restart: always

    ports:
      - "8085:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springboot3
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass

volumes:
  mysql_data:
